name: Normalize composer.json

on:
    push:
        paths:
            - "composer.json"

jobs:
    normalize:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Normalize composer.json
              run: |
                  composer global require ergebnis/composer-normalize
                  composer normalize

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Normalize composer.json
