name: PHPStan - Code Static Analysis

on:
    push:
        paths:
            - '**.php'
            - 'phpstan.neon.dist'
    # pull_request:
    #     paths:
    #         - '**.php'
    #         - 'phpstan.neon.dist'

jobs:

    phpstan:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['8.1', '8.0']

        name: "PHPStan | PHP: ${{ matrix.php }}"

        steps:

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Install Dependencies
              run: composer update --prefer-stable --prefer-dist --no-interaction --no-suggest --ansi

            - name: Run PHPStan
              run: ./vendor/bin/phpstan analyse --error-format=github --no-progress --ansi
